# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  workflow_dispatch:
  push:
      branches: [main]
  pull_request:
      branches: [main]

permissions:
  issues: read
  pull-requests: read
  actions: write      
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
            
      - uses: actions/cache@v4
        with:
          path: |
              ~/.npm
              ${{ github.workspace }}/.express/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-expressjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
              ${{ runner.os }}-expressjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Setup node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 22.x
      - run: npm ci
      - run: npm run build
      - run: npm test
      
